# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Tests

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  schedule:
      - cron: '59 23 * * *'
  workflow_dispatch:
    inputs:
      version:
        description: Manual Test Trigger
        default: test
        required: false

jobs:
  build:
    name: ${{ matrix.os }}, ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
       matrix:
         os: [ubuntu-latest]
         environment-file:
           - ci/37.yaml
           - ci/38.yaml
           - ci/39.yaml
    
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
       
      - name: setup micromamba
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: ${{ matrix.environment-file }}
          micromamba-version: 'latest'
      
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          python -m flake8 . --count --select E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          python -m flake8 . --count --exit-zero --max-complexity 10 --max-line-length 127 --statistics
      
      - name: Test docstrings
        run: |
          pytest -v --color yes --doctest-modules ./src/transbigdata
      
      - name: Test
        run: |
          pytest -v -r s --color yes --cov src --cov-append --cov-report term-missing --cov-report xml
      
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true
